### ISSUE TITLE
Gladiator Lancer - Aquilon Optics abitlity

### ISSUE THREAD

**Issue by eMarchenko** [korzxd/Unitcrunch-Indices#2]
The profile doesn't include this ability:
```
Aquilon Optics: 
Each time this model is selected to shoot, you can re-roll one Hit roll, 
you can re-roll one Wound roll and you can re-roll one Damage roll when resolving its attacks.
```
Afaik one cannot implement it correctly, but adding 1 re-roll of everything to the main gun should be a good approximation. 

That's my take on how `Lancer laser destroyer` may work:

<img width="985" alt="Screenshot 2023-09-09 at 12 14 20 AM" src="https://github.com/korzxd/Unitcrunch-Indices/assets/7409234/8d2ef765-fbd3-4958-a94c-fa73cf07e139">

**Comment by korzxd** [comment]
Thanks I vaguely remember doing a similar thing in another unit profile, I'll look into adding this aswell.
