### ISSUE TITLE
Techmarines - Vengeance of the Omnissiah ability not implemented

### ISSUE THREAD

**Issue by eMarchenko** [korzxd/Unitcrunch-Indices#4]
```
Vengeance of the Omnissiah: 
If a friendly Adeptus Astartes Vehicle model is destroyed within 12" of this model, 
until the end of the battle, this model’s Omnissian power axe has an Attacks characteristic of 7.
```

`Vengeance of the Omnissiah` ability of `Primaris Techmarine` and `Techmarine` is not implemented. One can do it as an additional melee weapon profile, similar to `Techmarine`'s Servo-arm.

**Comment by korzxd** [comment]
Good idea, i have implemented the weapon into the Primaris Techmarine But the Techmarine has reached the maximum weapon profiles and i'll add a short summary in the changelog on how to add the weapon if they wish to remove an existing weapon.
