### ISSUE TITLE
Bladeguard Veteran Squad - wrong weapon layout

### ISSUE THREAD

**Issue by eMarchenko** [korzxd/Unitcrunch-Indices#5]
`Bladeguard Veteran Squad x3` currently has 5 `Master-crafted power weapon` and 5 `Heavy bolt pistol`. 
It should have 3 and 2 respectively (the Sergeant has an alternative pistol).

**Comment by korzxd** [comment]
Implemented the change, the seargant can equip a Heavy Bolt Pistol though so I have kept the count per unit to the maximum of 3 to keep it inline with all the other profiles.

I've also added the Shields of Imperium ability as a profile ability now that Unitcrunch allows rerolls on Saves/inv saves.

Should have a release by the end of the week just got to find time to double check my changes.
