### ISSUE TITLE
Oath of Moment  suggestion

### ISSUE THREAD

**Issue by eMarchenko** [korzxd/Unitcrunch-Indices#6]
While using unitcrunch with this dataset, I found current `Oath of Moment` implementation slightly cumbersome:

- when I want to compare two attacking units, I have to check if they have the same `Oath of Moment` settings
- it bloats unit profile page and may reach technical limits for some units / collections(?)

I suggest moving it to the Global Modifiers section. I've tried it this way and it worked fine for me.
Besides, I've implemented `Armour of contempt` in the same section, so I can recreate different combat scenarios from one panel.

**Comment by dixhuit** [comment]
> I suggest moving it to the Global Modifiers section.

Agreed, this is the sort of thing that "Global" modifiers are designed to be used for.

**Comment by dixhuit** [comment]
> If Unitcrunch were to include an Import/Export & Alias features on Global modifiers

This is on the todo list already.
