### ISSUE TITLE
Rename repo

### ISSUE THREAD

**Issue by dixhuit** [korzxd/Unitcrunch-Indices#8]
"Indices" might have been a little short-sighted? :)

Suggestion: **"UnitCrunch-data-exports"** (changed to capital "C" while I'm at it).

I'd avoid "profiles", "datasheets", "units" etc as the UC data export will likely contain more than this in the future (e.g. custom global modifiers, custom tagging etc).

Keep up the great work!

**Comment by korzxd** [comment]
I agree, "UnitCrunch-data-exports" sounds better, will change this now 👍
